// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {craft} from '../models';

export function CheckOllama():Promise<backend.OllamaStatus>;

export function ClearCraft():Promise<void>;

export function Craft(arg1:string,arg2:string):Promise<backend.CraftResult>;

export function GetResources():Promise<Array<craft.Item>>;

export function GetUnlockables():Promise<Array<craft.Item>>;

export function UnlockElement(arg1:string):Promise<craft.Item>;
