// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckOllama() {
  return window['go']['main']['App']['CheckOllama']();
}

export function ClearCraft() {
  return window['go']['main']['App']['ClearCraft']();
}

export function Craft(arg1, arg2) {
  return window['go']['main']['App']['Craft'](arg1, arg2);
}

export function GetResources() {
  return window['go']['main']['App']['GetResources']();
}
