// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {craft} from '../models';

export function CheckOllama():Promise<main.OllamaStatus>;

export function ClearCraft():Promise<void>;

export function Craft(arg1:string,arg2:string):Promise<main.CraftResult>;

export function GetResources():Promise<Array<craft.Item>>;
